FROM node:18

WORKDIR /app

COPY frontend/package.json .
COPY frontend/vite.config.js .
COPY frontend/tailwind.config.js .
COPY frontend/postcss.config.cjs .
COPY frontend/public ./public
COPY frontend/src ./src

RUN npm install
RUN npm run build

# Serve dist with simple static server
RUN npm install -g serve
CMD ["serve", "-s", "dist", "-l", "3000"]
